// Code generated by protoc-gen-go.
// source: stored.proto
// DO NOT EDIT!

/*
Package stored is a generated protocol buffer package.

It is generated from these files:
	stored.proto

It has these top-level messages:
	Data
*/
package stored

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data_Type int32

const (
	Data_Normal Data_Type = 0
)

var Data_Type_name = map[int32]string{
	0: "Normal",
}
var Data_Type_value = map[string]int32{
	"Normal": 0,
}

func (x Data_Type) String() string {
	return proto.EnumName(Data_Type_name, int32(x))
}
func (Data_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Data struct {
	Payload []byte    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Type    Data_Type `protobuf:"varint,2,opt,name=type,enum=stored.Data_Type" json:"type,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Data) GetType() Data_Type {
	if m != nil {
		return m.Type
	}
	return Data_Normal
}

func init() {
	proto.RegisterType((*Data)(nil), "stored.Data")
	proto.RegisterEnum("stored.Data_Type", Data_Type_name, Data_Type_value)
}

func init() { proto.RegisterFile("stored.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0xc9, 0x2f,
	0x4a, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xa2, 0xb9, 0x58,
	0x5c, 0x12, 0x4b, 0x12, 0x85, 0x24, 0xb8, 0xd8, 0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x55, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x41, 0x3d, 0xa8, 0x31, 0x20, 0x5d, 0x7a, 0x21, 0x95,
	0x05, 0xa9, 0x41, 0x60, 0x69, 0x25, 0x21, 0x2e, 0x16, 0x10, 0x4f, 0x88, 0x8b, 0x8b, 0xcd, 0x2f,
	0xbf, 0x28, 0x37, 0x31, 0x47, 0x80, 0x21, 0x89, 0x0d, 0x6c, 0x97, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x81, 0x88, 0xeb, 0xe6, 0x7b, 0x00, 0x00, 0x00,
}
