// Code generated by protoc-gen-go.
// source: node.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	node.proto
	scheduler.proto

It has these top-level messages:
	BufferInfo
	WriteDataPacket
	ReadDataPacket
	WriteResponse
	InfoResponse
	CreateInfo
	CreateResponse
	ListInfo
	ListResponse
	ClusterInfo
	NodeInfo
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BufferInfo struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	StartIndex   uint64 `protobuf:"varint,2,opt,name=startIndex" json:"startIndex,omitempty"`
	StartFromEnd bool   `protobuf:"varint,3,opt,name=startFromEnd" json:"startFromEnd,omitempty"`
}

func (m *BufferInfo) Reset()                    { *m = BufferInfo{} }
func (m *BufferInfo) String() string            { return proto.CompactTextString(m) }
func (*BufferInfo) ProtoMessage()               {}
func (*BufferInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type WriteDataPacket struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *WriteDataPacket) Reset()                    { *m = WriteDataPacket{} }
func (m *WriteDataPacket) String() string            { return proto.CompactTextString(m) }
func (*WriteDataPacket) ProtoMessage()               {}
func (*WriteDataPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadDataPacket struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Index   uint64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *ReadDataPacket) Reset()                    { *m = ReadDataPacket{} }
func (m *ReadDataPacket) String() string            { return proto.CompactTextString(m) }
func (*ReadDataPacket) ProtoMessage()               {}
func (*ReadDataPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type WriteResponse struct {
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type InfoResponse struct {
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*BufferInfo)(nil), "pb.BufferInfo")
	proto.RegisterType((*WriteDataPacket)(nil), "pb.WriteDataPacket")
	proto.RegisterType((*ReadDataPacket)(nil), "pb.ReadDataPacket")
	proto.RegisterType((*WriteResponse)(nil), "pb.WriteResponse")
	proto.RegisterType((*InfoResponse)(nil), "pb.InfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Node service

type NodeClient interface {
	Write(ctx context.Context, opts ...grpc.CallOption) (Node_WriteClient, error)
	Read(ctx context.Context, in *BufferInfo, opts ...grpc.CallOption) (Node_ReadClient, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Write(ctx context.Context, opts ...grpc.CallOption) (Node_WriteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Node_serviceDesc.Streams[0], c.cc, "/pb.Node/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeWriteClient{stream}
	return x, nil
}

type Node_WriteClient interface {
	Send(*WriteDataPacket) error
	CloseAndRecv() (*WriteResponse, error)
	grpc.ClientStream
}

type nodeWriteClient struct {
	grpc.ClientStream
}

func (x *nodeWriteClient) Send(m *WriteDataPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeWriteClient) CloseAndRecv() (*WriteResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeClient) Read(ctx context.Context, in *BufferInfo, opts ...grpc.CallOption) (Node_ReadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Node_serviceDesc.Streams[1], c.cc, "/pb.Node/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Node_ReadClient interface {
	Recv() (*ReadDataPacket, error)
	grpc.ClientStream
}

type nodeReadClient struct {
	grpc.ClientStream
}

func (x *nodeReadClient) Recv() (*ReadDataPacket, error) {
	m := new(ReadDataPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Node service

type NodeServer interface {
	Write(Node_WriteServer) error
	Read(*BufferInfo, Node_ReadServer) error
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServer).Write(&nodeWriteServer{stream})
}

type Node_WriteServer interface {
	SendAndClose(*WriteResponse) error
	Recv() (*WriteDataPacket, error)
	grpc.ServerStream
}

type nodeWriteServer struct {
	grpc.ServerStream
}

func (x *nodeWriteServer) SendAndClose(m *WriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeWriteServer) Recv() (*WriteDataPacket, error) {
	m := new(WriteDataPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Node_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BufferInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServer).Read(m, &nodeReadServer{stream})
}

type Node_ReadServer interface {
	Send(*ReadDataPacket) error
	grpc.ServerStream
}

type nodeReadServer struct {
	grpc.ServerStream
}

func (x *nodeReadServer) Send(m *ReadDataPacket) error {
	return x.ServerStream.SendMsg(m)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Node",
	HandlerType: (*NodeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _Node_Write_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Node_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x9b, 0x76, 0xeb, 0x9f, 0x61, 0x6d, 0x75, 0xf4, 0xb0, 0xf4, 0x20, 0x4b, 0x4e, 0x7b,
	0x5a, 0xc4, 0x7e, 0x00, 0x45, 0x54, 0xe8, 0x45, 0x24, 0x17, 0xcf, 0x59, 0x33, 0x2b, 0x4b, 0xd9,
	0x64, 0x49, 0x52, 0xf0, 0xe3, 0x4b, 0xa2, 0xad, 0x59, 0xf1, 0x36, 0xbf, 0x97, 0x99, 0xcc, 0x7b,
	0x09, 0x80, 0x36, 0x8a, 0xea, 0xc1, 0x1a, 0x6f, 0x70, 0x3a, 0x34, 0x5c, 0x01, 0x3c, 0xec, 0xda,
	0x96, 0xec, 0x46, 0xb7, 0x06, 0x11, 0x32, 0x2d, 0x7b, 0x2a, 0x58, 0xc9, 0xaa, 0x53, 0x11, 0x6b,
	0xbc, 0x06, 0x70, 0x5e, 0x5a, 0xbf, 0xd1, 0x8a, 0x3e, 0x8b, 0x69, 0xc9, 0xaa, 0x4c, 0x24, 0x0a,
	0x72, 0xc8, 0x23, 0x3d, 0x5b, 0xd3, 0x3f, 0x69, 0x55, 0xcc, 0x4a, 0x56, 0x9d, 0x88, 0x91, 0xc6,
	0xef, 0x60, 0xf9, 0x66, 0x3b, 0x4f, 0x8f, 0xd2, 0xcb, 0x57, 0xf9, 0xbe, 0x25, 0xff, 0xef, 0xaa,
	0x02, 0x8e, 0x7b, 0x72, 0x4e, 0x7e, 0x50, 0xdc, 0x93, 0x8b, 0x3d, 0xf2, 0x7b, 0x58, 0x08, 0x92,
	0x2a, 0x99, 0x4f, 0x7a, 0xd9, 0xa8, 0x17, 0xaf, 0x60, 0xde, 0x25, 0x5e, 0xbf, 0x81, 0x2f, 0xe1,
	0x2c, 0x5a, 0x10, 0xe4, 0x06, 0xa3, 0x1d, 0xf1, 0x12, 0xf2, 0x90, 0x79, 0xcf, 0x78, 0x0e, 0xb3,
	0x9d, 0xed, 0x7e, 0xfc, 0x84, 0xf2, 0x76, 0x0b, 0xd9, 0x8b, 0x51, 0x84, 0x6b, 0x98, 0xc7, 0x51,
	0xbc, 0xac, 0x87, 0xa6, 0xfe, 0x13, 0x64, 0x75, 0x71, 0x10, 0x0f, 0x57, 0x4f, 0x2a, 0x86, 0x35,
	0x64, 0xc1, 0x31, 0x2e, 0xc2, 0xf1, 0xef, 0x13, 0xaf, 0x30, 0xf0, 0x38, 0x0b, 0x9f, 0xdc, 0xb0,
	0xe6, 0x28, 0xfe, 0xc9, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xca, 0x59, 0x6b, 0xa1, 0x01,
	0x00, 0x00,
}
