// Code generated by protoc-gen-go.
// source: scheduler.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	scheduler.proto
	talaria.proto

It has these top-level messages:
	CreateInfo
	CreateResponse
	ListInfo
	ListResponse
	ClusterInfo
	BufferInfo
	WriteDataPacket
	ReadDataPacket
	WriteResponse
	InfoResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateInfo) Reset()                    { *m = CreateInfo{} }
func (m *CreateInfo) String() string            { return proto.CompactTextString(m) }
func (*CreateInfo) ProtoMessage()               {}
func (*CreateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListInfo struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *ListInfo) Reset()                    { *m = ListInfo{} }
func (m *ListInfo) String() string            { return proto.CompactTextString(m) }
func (*ListInfo) ProtoMessage()               {}
func (*ListInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListResponse struct {
	Info []*ClusterInfo `protobuf:"bytes,1,rep,name=info" json:"info,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListResponse) GetInfo() []*ClusterInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ClusterInfo struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Leader string   `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
	Nodes  []string `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *ClusterInfo) Reset()                    { *m = ClusterInfo{} }
func (m *ClusterInfo) String() string            { return proto.CompactTextString(m) }
func (*ClusterInfo) ProtoMessage()               {}
func (*ClusterInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*CreateInfo)(nil), "pb.CreateInfo")
	proto.RegisterType((*CreateResponse)(nil), "pb.CreateResponse")
	proto.RegisterType((*ListInfo)(nil), "pb.ListInfo")
	proto.RegisterType((*ListResponse)(nil), "pb.ListResponse")
	proto.RegisterType((*ClusterInfo)(nil), "pb.ClusterInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Scheduler service

type SchedulerClient interface {
	Create(ctx context.Context, in *CreateInfo, opts ...grpc.CallOption) (*CreateResponse, error)
	ListClusterInfo(ctx context.Context, in *ListInfo, opts ...grpc.CallOption) (*ListResponse, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) Create(ctx context.Context, in *CreateInfo, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/pb.Scheduler/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListClusterInfo(ctx context.Context, in *ListInfo, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/pb.Scheduler/ListClusterInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scheduler service

type SchedulerServer interface {
	Create(context.Context, *CreateInfo) (*CreateResponse, error)
	ListClusterInfo(context.Context, *ListInfo) (*ListResponse, error)
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scheduler/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Create(ctx, req.(*CreateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scheduler/ListClusterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListClusterInfo(ctx, req.(*ListInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Scheduler_Create_Handler,
		},
		{
			MethodName: "ListClusterInfo",
			Handler:    _Scheduler_ListClusterInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("scheduler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x6b, 0x02, 0x31,
	0x10, 0x85, 0xbb, 0x6a, 0x97, 0xee, 0x28, 0xae, 0x0c, 0xa5, 0x2c, 0x9e, 0x42, 0x7a, 0xf1, 0x94,
	0x83, 0xfb, 0x13, 0x3c, 0x15, 0x0a, 0x85, 0xf4, 0x17, 0xec, 0x76, 0x47, 0x2a, 0x6c, 0x93, 0x90,
	0xc4, 0xff, 0x5f, 0x32, 0x6b, 0xd4, 0x83, 0xb7, 0xbc, 0xc9, 0x7b, 0xc9, 0xfb, 0x06, 0xea, 0xf0,
	0xf3, 0x4b, 0xc3, 0x79, 0x24, 0xaf, 0x9c, 0xb7, 0xd1, 0xe2, 0xcc, 0xf5, 0x52, 0x00, 0x1c, 0x3c,
	0x75, 0x91, 0x3e, 0xcc, 0xd1, 0x22, 0xc2, 0xc2, 0x74, 0x7f, 0xd4, 0x14, 0xa2, 0xd8, 0x55, 0x9a,
	0xcf, 0x72, 0x03, 0xeb, 0xc9, 0xa1, 0x29, 0x38, 0x6b, 0x02, 0x49, 0x01, 0x2f, 0x9f, 0xa7, 0x10,
	0x39, 0xf1, 0x0a, 0xcf, 0xc9, 0x15, 0x9a, 0x42, 0xcc, 0x77, 0x95, 0x9e, 0x84, 0x6c, 0x61, 0x95,
	0x1c, 0x39, 0x81, 0xef, 0xb0, 0x38, 0x99, 0xa3, 0x65, 0xd3, 0x72, 0x5f, 0x2b, 0xd7, 0xab, 0xc3,
	0x78, 0x0e, 0x91, 0x7c, 0x7a, 0x44, 0xf3, 0xa5, 0xfc, 0x82, 0xe5, 0xdd, 0xf0, 0x51, 0x17, 0x7c,
	0x83, 0x72, 0xa4, 0x6e, 0x20, 0xdf, 0xcc, 0x78, 0x7a, 0x51, 0xdc, 0xc2, 0x0e, 0x14, 0x9a, 0xf9,
	0xa5, 0x45, 0x12, 0x7b, 0x07, 0xd5, 0x77, 0x46, 0x46, 0x05, 0xe5, 0x84, 0x81, 0x6b, 0xfe, 0xfe,
	0x0a, 0xbd, 0xc5, 0x9b, 0xbe, 0x22, 0x3e, 0x61, 0x0b, 0x75, 0x42, 0xb8, 0x6f, 0xb4, 0x4a, 0xc6,
	0x4c, 0xbe, 0xdd, 0x64, 0x75, 0x0b, 0xf5, 0x25, 0x2f, 0xb6, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xfb, 0xfd, 0xff, 0x06, 0x6b, 0x01, 0x00, 0x00,
}
