// Code generated by protoc-gen-go.
// source: talaria.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	talaria.proto

It has these top-level messages:
	File
	WriteDataPacket
	ReadDataPacket
	CreateResponse
	WriteResponse
	InfoResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	FileName   string `protobuf:"bytes,1,opt,name=fileName" json:"fileName,omitempty"`
	StartIndex uint64 `protobuf:"varint,2,opt,name=startIndex" json:"startIndex,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type WriteDataPacket struct {
	FileName string `protobuf:"bytes,1,opt,name=fileName" json:"fileName,omitempty"`
	Message  []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *WriteDataPacket) Reset()                    { *m = WriteDataPacket{} }
func (m *WriteDataPacket) String() string            { return proto.CompactTextString(m) }
func (*WriteDataPacket) ProtoMessage()               {}
func (*WriteDataPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadDataPacket struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Index   uint64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *ReadDataPacket) Reset()                    { *m = ReadDataPacket{} }
func (m *ReadDataPacket) String() string            { return proto.CompactTextString(m) }
func (*ReadDataPacket) ProtoMessage()               {}
func (*ReadDataPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CreateResponse struct {
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type WriteResponse struct {
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type InfoResponse struct {
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*WriteDataPacket)(nil), "pb.WriteDataPacket")
	proto.RegisterType((*ReadDataPacket)(nil), "pb.ReadDataPacket")
	proto.RegisterType((*CreateResponse)(nil), "pb.CreateResponse")
	proto.RegisterType((*WriteResponse)(nil), "pb.WriteResponse")
	proto.RegisterType((*InfoResponse)(nil), "pb.InfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Talaria service

type TalariaClient interface {
	Create(ctx context.Context, in *File, opts ...grpc.CallOption) (*CreateResponse, error)
	Write(ctx context.Context, opts ...grpc.CallOption) (Talaria_WriteClient, error)
	Read(ctx context.Context, in *File, opts ...grpc.CallOption) (Talaria_ReadClient, error)
	Info(ctx context.Context, in *File, opts ...grpc.CallOption) (*InfoResponse, error)
}

type talariaClient struct {
	cc *grpc.ClientConn
}

func NewTalariaClient(cc *grpc.ClientConn) TalariaClient {
	return &talariaClient{cc}
}

func (c *talariaClient) Create(ctx context.Context, in *File, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/pb.Talaria/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talariaClient) Write(ctx context.Context, opts ...grpc.CallOption) (Talaria_WriteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Talaria_serviceDesc.Streams[0], c.cc, "/pb.Talaria/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &talariaWriteClient{stream}
	return x, nil
}

type Talaria_WriteClient interface {
	Send(*WriteDataPacket) error
	CloseAndRecv() (*WriteResponse, error)
	grpc.ClientStream
}

type talariaWriteClient struct {
	grpc.ClientStream
}

func (x *talariaWriteClient) Send(m *WriteDataPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *talariaWriteClient) CloseAndRecv() (*WriteResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *talariaClient) Read(ctx context.Context, in *File, opts ...grpc.CallOption) (Talaria_ReadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Talaria_serviceDesc.Streams[1], c.cc, "/pb.Talaria/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &talariaReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Talaria_ReadClient interface {
	Recv() (*ReadDataPacket, error)
	grpc.ClientStream
}

type talariaReadClient struct {
	grpc.ClientStream
}

func (x *talariaReadClient) Recv() (*ReadDataPacket, error) {
	m := new(ReadDataPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *talariaClient) Info(ctx context.Context, in *File, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/pb.Talaria/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Talaria service

type TalariaServer interface {
	Create(context.Context, *File) (*CreateResponse, error)
	Write(Talaria_WriteServer) error
	Read(*File, Talaria_ReadServer) error
	Info(context.Context, *File) (*InfoResponse, error)
}

func RegisterTalariaServer(s *grpc.Server, srv TalariaServer) {
	s.RegisterService(&_Talaria_serviceDesc, srv)
}

func _Talaria_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalariaServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Talaria/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalariaServer).Create(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _Talaria_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TalariaServer).Write(&talariaWriteServer{stream})
}

type Talaria_WriteServer interface {
	SendAndClose(*WriteResponse) error
	Recv() (*WriteDataPacket, error)
	grpc.ServerStream
}

type talariaWriteServer struct {
	grpc.ServerStream
}

func (x *talariaWriteServer) SendAndClose(m *WriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *talariaWriteServer) Recv() (*WriteDataPacket, error) {
	m := new(WriteDataPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Talaria_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(File)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TalariaServer).Read(m, &talariaReadServer{stream})
}

type Talaria_ReadServer interface {
	Send(*ReadDataPacket) error
	grpc.ServerStream
}

type talariaReadServer struct {
	grpc.ServerStream
}

func (x *talariaReadServer) Send(m *ReadDataPacket) error {
	return x.ServerStream.SendMsg(m)
}

func _Talaria_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalariaServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Talaria/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalariaServer).Info(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

var _Talaria_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Talaria",
	HandlerType: (*TalariaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Talaria_Create_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Talaria_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _Talaria_Write_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Talaria_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("talaria.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xed, 0xd6, 0xf4, 0xc3, 0xa1, 0x5f, 0x8e, 0x1e, 0x42, 0x0e, 0x12, 0x16, 0x0f, 0x39, 0x05,
	0xb1, 0x7f, 0x40, 0x54, 0x94, 0x5e, 0x44, 0x82, 0xe0, 0x79, 0x62, 0xa7, 0xb2, 0x98, 0x26, 0x61,
	0x77, 0x05, 0x7f, 0x9a, 0x3f, 0x4f, 0x36, 0xb1, 0x75, 0x53, 0xd0, 0xdb, 0xbc, 0xc9, 0x9b, 0xf7,
	0x5e, 0xde, 0xc2, 0xd4, 0x52, 0x41, 0x5a, 0x51, 0x5a, 0xeb, 0xca, 0x56, 0xd8, 0xaf, 0x73, 0x79,
	0x03, 0xc1, 0xbd, 0x2a, 0x18, 0x23, 0x18, 0x6f, 0x54, 0xc1, 0x8f, 0xb4, 0xe5, 0x50, 0xc4, 0x22,
	0x39, 0xce, 0xf6, 0x18, 0xcf, 0x01, 0x8c, 0x25, 0x6d, 0x57, 0xe5, 0x9a, 0x3f, 0xc3, 0x7e, 0x2c,
	0x92, 0x20, 0xf3, 0x36, 0xf2, 0x01, 0xe6, 0x2f, 0x5a, 0x59, 0xbe, 0x23, 0x4b, 0x4f, 0xf4, 0xfa,
	0xce, 0xf6, 0x5f, 0xb9, 0x10, 0x46, 0x5b, 0x36, 0x86, 0xde, 0xb8, 0xd1, 0x9a, 0x64, 0x3b, 0x28,
	0xaf, 0x61, 0x96, 0x31, 0xad, 0x3d, 0x1d, 0x8f, 0x2b, 0x3a, 0x5c, 0x3c, 0x83, 0x81, 0xf2, 0xf2,
	0xb4, 0x40, 0x4a, 0x98, 0xdd, 0x6a, 0x26, 0xcb, 0x19, 0x9b, 0xba, 0x2a, 0x0d, 0xe3, 0x02, 0x8e,
	0x3e, 0xb4, 0xfa, 0x09, 0xe1, 0x46, 0x39, 0x87, 0x69, 0x13, 0x77, 0x47, 0x91, 0x31, 0x4c, 0x56,
	0xe5, 0xa6, 0xfa, 0xfb, 0xe4, 0xea, 0x4b, 0xc0, 0xe8, 0xb9, 0xed, 0x0e, 0x13, 0x18, 0xb6, 0x16,
	0x38, 0x4e, 0xeb, 0x3c, 0x75, 0xed, 0x45, 0xe8, 0xa6, 0xae, 0xb1, 0xec, 0xe1, 0x12, 0x06, 0x8d,
	0x11, 0x9e, 0xba, 0xcf, 0x07, 0x15, 0x45, 0x27, 0xfb, 0xe5, 0xef, 0x49, 0x22, 0x30, 0x81, 0xc0,
	0x75, 0x70, 0x28, 0xde, 0xed, 0x45, 0xf6, 0x2e, 0x05, 0x5e, 0x40, 0xe0, 0x62, 0x7b, 0xcc, 0x85,
	0x9b, 0xfc, 0x5f, 0x91, 0xbd, 0x7c, 0xd8, 0xbc, 0xf5, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x03,
	0x10, 0x6b, 0xe6, 0xfc, 0x01, 0x00, 0x00,
}
