// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package intraserver_test

type mockIOFetcher struct {
	CreateCalled chan bool
	CreateInput  struct {
		Name chan string
	}
	CreateOutput struct {
		Ret0 chan error
	}
}

func newMockIOFetcher() *mockIOFetcher {
	m := &mockIOFetcher{}
	m.CreateCalled = make(chan bool, 100)
	m.CreateInput.Name = make(chan string, 100)
	m.CreateOutput.Ret0 = make(chan error, 100)
	return m
}
func (m *mockIOFetcher) Create(name string) error {
	m.CreateCalled <- true
	m.CreateInput.Name <- name
	return <-m.CreateOutput.Ret0
}
